In [3]:
import tensorflow as tf
import numpy as np

In [17]:
X_data = np.random.random((10000, 2))
print(X_data[:4, :])
sample_weight = np.array([3, 4]).reshape(2,)
print(sample_weight)
y_data = np.matmul(X_data, sample_weight)
print(y_data)

[[0.4900147  0.94670714]
 [0.23961841 0.55592574]
 [0.09295993 0.64359425]
 [0.22664181 0.66745991]]
[3 4]
[5.25687264 2.94255818 2.85325677 ... 2.72749054 2.37339296 2.67026431]


In [18]:
# Approximation Y
y_data = np.add(y_data, np.random.uniform(-0.5, 0.5))
print(y_data)

[5.70030706 3.38599259 3.29669118 ... 3.17092496 2.81682738 3.11369872]


In [20]:
y_data.shape

(10000,)

In [21]:
y_data = y_data.reshape(len(y_data), 1)
y_data.shape

(10000, 1)

## Nếu training đúng sẽ ra kết quả = (3, 4)

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_data, y_data, test_size=0.2, random_state=42)

In [25]:
X_train.shape
y_train.shape

(8000, 1)

In [29]:
# import tensorflow.compat.v1 as tf
# tf.disable_v2_behavior() 
# n_dim = X_train.shape[1]
# X = tf.placeholder(tf.float32, [None, n_dim])

In [44]:
from tensorflow import keras
n_dim = X_train.shape[1]
X = keras.layers.Input(shape = (n_dim))
y = keras.layers.Input(shape = (1))

In [45]:
print(X)
print(y)

Tensor("input_7:0", shape=(?, 2), dtype=float32)
Tensor("input_8:0", shape=(?, 1), dtype=float32)


In [54]:
W = tf.Variable( tf.ones([n_dim,1]))
b = tf.Variable(np.random.randn(), dtype=tf.float32)

In [55]:
pred = tf.add(tf.matmul(X, W), b)

In [57]:
loss = tf.reduce_mean(tf.square(pred-y))

In [58]:
learning_rate = 0.01
optimezer = tf.train.GradientDescentOptimizer(learning_rate= learning_rate).minimize(loss)

In [59]:
init = tf.global_variables_initializer()

In [ ]:
# Training
epochs = 1000
# optimezer = tf.keras.optimizers.Adadelta()