In [1]:
import tensorflow as tf

In [3]:
tensor_2 = tf.constant([[23, 4], [32, 5]])
tensor_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32,  5]])>

In [4]:
tensor_2.shape

TensorShape([2, 2])

In [5]:
tensor_2.numpy()

array([[23,  4],
       [32,  5]])

## New 1: Convert a np to tensor

In [6]:
import numpy as np
numpy_tensor = np.array([[22, 3], [11, 3]])
tensor_from_numpy = tf.constant(numpy_tensor)
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22,  3],
       [11,  3]])>

## using np with tensor 

In [8]:
np.square(tensor_2)
np.sqrt(tensor_2)

array([[4.79583152, 2.        ],
       [5.65685425, 2.23606798]])

# New 2:  dot 

In [9]:
np.dot(tensor_2, tensor_from_numpy)

array([[550,  81],
       [759, 111]])

# Operations with variable

In [10]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [11]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [12]:
tf2_variable[0,2].assign(1000)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[   1.,    2., 1000.],
       [   4.,    5.,    6.]], dtype=float32)>

 https://www.youtube.com/watch?v=3O-5DuqKaRo